sudo: false

language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.3.1

bundler_args: --without development doc

before_install: gem install bundler -v 1.12.5

addons:
  code_climate:
    repo_token: 97786ceac8f7388a6ac89408a63f98454678567c780deef82377f8e66b9f7cd6
